# Generated by Django 4.2.16 on 2024-12-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='acordo_id',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Finalizado', 'Finalizado')], default='Pendente', max_length=50),
        ),
    ]
