# Generated by Django 4.2.16 on 2024-12-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_agendamento_acordo_id_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
