# Generated by Django 4.2.16 on 2024-12-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agendamento_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CHEQUE', 'Cheque'), ('PAGAMENTO_LOJA', 'Pagamento na Loja')], max_length=20, null=True),
        ),
    ]
