# Generated by Django 4.2.16 on 2024-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parcelamento_data_vencimento_parcela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devedor',
            name='email3',
        ),
        migrations.RemoveField(
            model_name='devedor',
            name='telefone12',
        ),
        migrations.RemoveField(
            model_name='devedor',
            name='telefone_marcos',
        ),
        migrations.AddField(
            model_name='parcelamento',
            name='data_vencimento_parcela',
            field=models.DateField(blank=True, null=True),
        ),
    ]
