# Generated by Django 4.2.16 on 2024-12-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_devedor_email3_remove_devedor_telefone12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='ultima_acao',
            field=models.DateField(blank=True, null=True, verbose_name='Última Ação'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.devedor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.empresa')),
            ],
        ),
    ]
