# Generated by Django 4.2.16 on 2025-01-27 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_titulo_ultima_acao_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('categoria', models.CharField(choices=[('Pendentes', 'Pendentes'), ('Negociados', 'Negociados'), ('Boletos', 'Boletos'), ('Cobrança boleto atrasado', 'Cobrança boleto atrasado'), ('Novo cliente', 'Novo cliente')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaRemuneracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='devedor',
            name='primeira_mensagem_cadastro',
        ),
        migrations.AddField(
            model_name='acordo',
            name='forma_pag_Id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='acordo_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do acordo'),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone10_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone1_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone2_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone3_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone4_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone5_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone6_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone7_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone8_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone9_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='devedor',
            name='telefone_valido',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('NAO VERIFICADO', 'NAO VERIFICADO')], default='NAO VERIFICADO', max_length=15),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='parcelamento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='dias_atraso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='statusBaixaGeral',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status da Baixa'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='rg_socio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='uf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cpf_contato',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valor_adesao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='devedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.devedor'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='core_empresa',
        ),
        migrations.AlterModelTable(
            name='followup',
            table='follow_up',
        ),
        migrations.CreateModel(
            name='UsersLojistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.IntegerField(default=0)),
                ('email_credit', models.IntegerField(default=0)),
                ('whatsapp_credit', models.CharField(default='0', max_length=299)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=191, null=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_user_access_log',
            },
        ),
        migrations.CreateModel(
            name='TabelaRemuneracaoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_dias', models.IntegerField()),
                ('ate_dias', models.IntegerField()),
                ('percentual_remuneracao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tabela_remuneracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='core.tabelaremuneracao')),
            ],
            options={
                'db_table': 'core_TabelaRemuneracaoLista',
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tabelaremuneracao'),
        ),
    ]
