# Generated by Django 4.2.16 on 2025-02-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mensagemwhatsapp_tabelaremuneracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('autenticacao', models.CharField(choices=[('SSL', 'SSL'), ('TLS', 'TLS')], max_length=3)),
                ('porta', models.IntegerField()),
                ('servidor_smtp', models.CharField(max_length=255)),
                ('tipo_envio', models.CharField(choices=[('Quitação Parcela', 'Quitação Parcela'), ('Quitação Contrato', 'Quitação Contrato'), ('Nova Empresa', 'Nova Empresa'), ('Negociação', 'Negociação'), ('Boleto', 'Boleto')], max_length=50)),
                ('provedor', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'emails_envio',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(choices=[('Quitação Parcela', 'Quitação Parcela'), ('Quitação Contrato', 'Quitação Contrato'), ('Nova Empresa', 'Nova Empresa'), ('Negociação', 'Negociação'), ('Boleto', 'Boleto')], max_length=50)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_favorecido_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status_empresa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
