# Generated by Django 4.2.16 on 2025-02-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailenvio_emailtemplate_empresa_nome_favorecido_pix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('codigo_solicitacao', models.CharField(blank=True, max_length=255, null=True)),
                ('seu_numero', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_situacao', models.DateField(blank=True, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem_recebimento', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cobranca', models.CharField(blank=True, max_length=50, null=True)),
                ('pagador_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('pagador_cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('nosso_numero', models.CharField(blank=True, max_length=255, null=True)),
                ('linha_digitavel', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True)),
                ('pix_copia_e_cola', models.TextField(blank=True, null=True)),
                ('txid', models.CharField(blank=True, max_length=255, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cobranca_enviada_whatsapp', models.CharField(blank=True, default='NAO', max_length=4, null=True)),
            ],
        ),
    ]
