# Generated by Django 4.2.16 on 2025-02-12 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_operados', to=settings.AUTH_USER_MODEL),
        ),
    ]
