# Generated by Django 4.2.16 on 2025-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_titulo_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='operador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operador'),
        ),
    ]
